/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/artlab/catkin_ws/src/test_suivi/srv/SendPose.srv
 *
 */


#ifndef TEST_SUIVI_MESSAGE_SENDPOSE_H
#define TEST_SUIVI_MESSAGE_SENDPOSE_H

#include <ros/service_traits.h>


#include <test_suivi/SendPoseRequest.h>
#include <test_suivi/SendPoseResponse.h>


namespace test_suivi
{

struct SendPose
{

typedef SendPoseRequest Request;
typedef SendPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendPose
} // namespace test_suivi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_suivi::SendPose > {
  static const char* value()
  {
    return "24dd8748a811e06ceaa50ae2d2754ada";
  }

  static const char* value(const ::test_suivi::SendPose&) { return value(); }
};

template<>
struct DataType< ::test_suivi::SendPose > {
  static const char* value()
  {
    return "test_suivi/SendPose";
  }

  static const char* value(const ::test_suivi::SendPose&) { return value(); }
};


// service_traits::MD5Sum< ::test_suivi::SendPoseRequest> should match 
// service_traits::MD5Sum< ::test_suivi::SendPose > 
template<>
struct MD5Sum< ::test_suivi::SendPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_suivi::SendPose >::value();
  }
  static const char* value(const ::test_suivi::SendPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_suivi::SendPoseRequest> should match 
// service_traits::DataType< ::test_suivi::SendPose > 
template<>
struct DataType< ::test_suivi::SendPoseRequest>
{
  static const char* value()
  {
    return DataType< ::test_suivi::SendPose >::value();
  }
  static const char* value(const ::test_suivi::SendPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_suivi::SendPoseResponse> should match 
// service_traits::MD5Sum< ::test_suivi::SendPose > 
template<>
struct MD5Sum< ::test_suivi::SendPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_suivi::SendPose >::value();
  }
  static const char* value(const ::test_suivi::SendPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_suivi::SendPoseResponse> should match 
// service_traits::DataType< ::test_suivi::SendPose > 
template<>
struct DataType< ::test_suivi::SendPoseResponse>
{
  static const char* value()
  {
    return DataType< ::test_suivi::SendPose >::value();
  }
  static const char* value(const ::test_suivi::SendPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_SUIVI_MESSAGE_SENDPOSE_H
