global_costmap:

  map_type: costmap
  track_unknown_space: true
  unknown_cost_value: 255
  obstacle_range: 2.0
  raytrace_range: 5.0
  footprint: [[0.15, 0.30], [0.15, -0.25], [-0.15, -0.25], [-0.15, 0.30]]
  inflation_radius: 2.0
  #transform_tolerance: 0.5
  inscribed_radius: 0.15
  circumscribed_radius: 0.33

  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 1.0
  publish_frequency: 0.0
  static_map: true
  rolling_window: false

  #Investigate what this actually does
  cost_scaling_factor: 10.0
  
  transform_tolerance: 10.0


local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
